#!/bin/bash

compressimages() {
  rm -rf compressedimages
  mkdir -p compressedimages || { echo "Failed to create directory 'compressedimages'"; return 1; }

  for image in $(docker images --format "{{.Repository}}:{{.Tag}}" | grep '^tools-int-01\.ccr\.xdmod\.org'); do
    imagename=$(echo "$image" | tr '/' '_' | tr ':' '_')
    docker save "$image" | gzip > "compressedimages/${imagename}.tar.gz"
    if [ $? -eq 0 ]; then
      echo "Saved and compressed $image"
    else
      echo "Failed to save and compress $image"
    fi
  done

  echo "Done!"
}


loadimages() {
  cd compressedimages || { echo "Failed to change directory to 'compressedimages'"; return 1; }

  for file in *.tar.gz; do
    docker load < "$file"
    if [ $? -eq 0 ]; then
      echo "Loaded Docker image from $file"
    else
      echo "Failed to load Docker image from $file"
    fi
  done
}


case "$1" in
  'save')
    compressimages
    ;;
  'load')
    loadimages
    ;;
  *)
    echo "Usage: $0 { save | load }"
    exit 1
    ;;
esac
