#!/bin/bash

log_info() {
    printf "\n\e[0;35m $1\e[0m\n\n"
}


log_warn() {
    printf "\e[0;33m $1\e[0m\n"
}


buildxdmod() {
    ./xdmodbuilder xdmod
    cd xdmod
    ./xdmodup build
    echo committing xdmod
    docker commit xdmod ${XDMOD_IMAGE}-build
    echo commited xdmod image
    cp .env ../.env
}


buildtestxdmod() {
    ./xdmodbuilder xdmod
    cd xdmod
    ./xdmodup build
    ./xdmodup stop
    ./xdmodup testbuild
    cp .env ../.env
}


buildondemand() {
  ./xdmodbuilder xdmod
  cd xdmod
  ./xdmodup build
  ./xdmodup stop
  cd ..
  ./xdmodbuilder ondemand
  cd xdmod-ondemand
  ./ondemand build
  cp .env ../xdmod/.env
}


testbuildondemand() {
  ./xdmodbuilder xdmod
  cd xdmod
  ./xdmodup build
  ./xdmodup stop
  ./xdmodup testbuild
  ./xdmodup stop
  cd ..
  ./xdmodbuilder testondemand
  cd xdmod-ondemand
  ./ondemand testbuild
  cp .env ../xdmod/.env
}

supremm() {
  ./xdmodbuilder xdmod
  cd xdmod
  ./xdmodup build
  ./xdmodup stop
  cd ..
  ./xdmodbuilder supremm
  cd xdmod-job-performance
  ./supremm build
  cp .env ../xdmod/.env
}


testsupremm() {
  ./xdmodbuilder xdmod
  cd xdmod
  ./xdmodup build
  ./xdmodup stop
  ./xdmodup testbuild
  ./xdmodup stop
  cd ..
  ./xdmodbuilder testsupremm
  cd xdmod-job-performance
  ./supremm testbuild
  cp .env ../xdmod/.env
}


resetenv() {
  rm -f .env
  wget https://raw.githubusercontent.com/ShixinWu16/create-docker-images/main/.env
}

case "$1" in
    'xdmod')
        buildxdmod
        ;;
    'testxdmod')
        buildtestxdmod
        ;;
    'ondemand')
        buildondemand
        ;;
    'testondemand')
        testbuildondemand
        ;;
    'supremm')
        supremm
        ;;
    'testsupremm')
        testsupremm
        ;;
    'resetenv')
        resetenv
        ;;
        *)
        log_info "Usage: $0 { xdmod | testxdmod | testondemand | ondemand | testsupremm | supremm | resetenv }"
        exit 1
        ;;
esac
