#!/bin/bash

log_info() {
    printf "\n\e[0;35m $1\e[0m\n\n"
}

log_warn() {
    printf "\e[0;33m $1\e[0m\n"
}


buildxdmod() {
    rm -f xdmod/.env
    cp .env xdmod/.env
    docker-compose build xdmod-base
    docker-compose build xdmod
    docker-compose build mariadb
}

buildondemand() {
    rm -f xdmod-ondemand/.env
    cp xdmod/.env xdmod-ondemand/.env
    source xdmod-ondemand/.env
    export XDMOD_IMAGE=${XDMOD_BUILD}
    docker-compose build xdmod-ondemand
}

buildtestondemand() {
    rm -f xdmod-ondemand/.env
    cp xdmod/.env xdmod-ondemand/.env
    source xdmod-ondemand/.env
    export XDMOD_IMAGE=${XDMOD_TESTBUILD}
    docker-compose build xdmod-ondemand
}

buildsupremm() {
    rm -f xdmod-job-performance/.env
    cp xdmod/.env xdmod-job-performance/.env
    source xdmod-job-performance/.env
    export XDMOD_IMAGE=${XDMOD_BUILD}
    docker-compose build xdmod-job-performance
    docker-compose build mongodb
}

buildtestsupremm() {
    rm -f xdmod-job-performance/.env
    cp xdmod/.env xdmod-job-performance/.env
    source xdmod-job-performance/.env
    export XDMOD_IMAGE=${XDMOD_TESTBUILD}
    docker-compose build xdmod-job-performance
    docker-compose build mongodb
}

resetenv() {
    rm -f .env
    wget https://raw.githubusercontent.com/ShixinWu16/create-docker-images/main/.env
}


case "$1" in
    'xdmod')
        buildxdmod
        ;;
    'ondemand')
        if grep -q '^XDMOD_BUILD=' .env;
        then
            buildondemand
        else
            log_info "Usage: $0 { buildondemand { Finish all of xdmod's builds first } }"
            exit 1
        fi
        ;;
    'supremm')
        if grep -q '^XDMOD_BUILD=' .env;
        then
            buildsupremm
        else
            log_info "Usage: $0 { buildsupremm { Finish all of xdmod's builds first } }"
            exit 1
        fi
        ;;
    'testondemand')
        if grep -q '^XDMOD_TESTBUILD=' .env;
        then
            buildtestondemand
        else
            log_info "Usage: $0 { buildondemand { Finish all of xdmod's builds first } }"
            exit 1
        fi
        ;;
    'testsupremm')
        if grep -q '^XDMOD_TESTBUILD=' .env;
        then
            buildtestsupremm
        else
            log_info "Usage: $0 { Finish all of xdmod's builds first }"
            exit 1
        fi
        ;;

      'resetenv')
          resetenv
          ;;
      *)
        log_info "Usage: $0 { xdmod | testondemand | ondemand | testsupremm | supremm | resetenv }"
        exit 1
        ;;
esac
