services:
  xdmod-ondemand:
    depends_on:
      mariadb:
        condition: service_healthy
    image: ${XDMOD_ONDEMAND_IMAGE}
    container_name: xdmod
    hostname: xdmod
    ports:
      - '443:443'
    networks:
      xdmod_default: {}

  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: tools-int-01.ccr.xdmod.org/mariadb:x86_64-rockylinux8.5-01-populated3
    restart: always
    volumes:
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--connect", "--innodb_initialized",  "--datadir", "/var/lib/db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      xdmod_default: {}

networks:
  xdmod_default:
    name: xdmod_default
