services:
  xdmod-ondemand:
    depends_on:
      mariadb:
        condition: service_healthy
    image: ${XDMOD_ONDEMAND_IMAGE}
    command: ${COMMAND}
    container_name: xdmod
    hostname: xdmod
    ports:
      - '443:443'
    networks:
      xdmod_default: {}

  mariadb:
    image: ${MARIADB_IMAGE}
    container_name: mariadb
    hostname: mariadb
    restart: always
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--connect", "--innodb_initialized",  "--datadir", "/var/lib/db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      xdmod_default: {}

networks:
  xdmod_default:
    name: xdmod_default
