#!/bin/bash

log_info() {
    printf "\n\e[0;35m $1\e[0m\n\n"
}

log_warn() {
    printf "\e[0;33m $1\e[0m\n"
}

# starts existing image
start() {
    source .env
    export XDMOD_ONDEMAND_IMAGE=${ONDEMAND_MARIADB_BUILD}
    export MARIADB_IMAGE=${ONDEMAND_MARIADB_BUILD}
    export COMMAND="start"
    docker-compose up -d
}


build() {
    source .env
    export MARIADB_IMAGE=${MARIADB_BUILD}
    export COMMAND="build"
    docker-compose up -d
    dots="."
    while ! curl --insecure --output /dev/null --silent --head --fail "https://localhost";
    do
      echo -ne "waiting for ondemand to be setup $dots\033[0K\r"
      sleep 1s
      dots="$dots."
      if [ ${#dots} -gt 3 ]; then
          dots="."
      fi
    done
    echo -e "\ondemand is up!"
    echo committing mariadb
    docker commit mariadb "${MARIADB_IMAGE}"-ondemand
    echo commited mariadb image
      if grep -q '^ONDEMAND_MARIADB_BUILD=' .env;
      then
        sed -i~ '/^ONDEMAND_MARIADB_BUILD=/s/=.*/=${MARIADB_IMAGE}-ondemand/' .env
      else
        echo "ONDEMAND_MARIADB_BUILD=${MARIADB_IMAGE}-ondemand" >> .env
      fi
      echo committing xdmod
      docker commit xdmod ${XDMOD_ONDEMAND_IMAGE}-build-ondemand
      echo commited xdmod image
      if grep -q '^ONDEMAND_BUILD=' .env;
      then
        sed -i~ '/^ONDEMAND_BUILD=/s/=.*/=${XDMOD_ONDEMAND_IMAGE}-build-ondemand/' .env
      else
        echo "ONDEMAND_BUILD=${XDMOD_ONDEMAND_IMAGE}-build-ondemand" >> .env
      fi
}

testbuild() {
    source .env
    export MARIADB_IMAGE=${MARIADB_TESTBUILD}
    export COMMAND="testbuild"
    docker-compose up -d
    dots="."
    while ! curl --insecure --output /dev/null --silent --head --fail "https://localhost";
    do
      echo -ne "waiting for Test ondemand to be setup $dots\033[0K\r"
      sleep 1s
      dots="$dots."
      if [ ${#dots} -gt 3 ]; then
          dots="."
      fi
    done
    echo -e "\Test ondemand is up!"
    echo committing mariadb
    docker commit mariadb "${MARIADB_IMAGE}"-ondemand
    echo commited mariadb image
    if grep -q '^ONDEMAND_MARIADB_TESTBUILD=' .env;
    then
      sed -i~ '/^ONDEMAND_MARIADB_TESTBUILD=/s/=.*/=${MARIADB_IMAGE}-ondemand/' .env
    else
      echo "ONDEMAND_MARIADB_TESTBUILD=${MARIADB_IMAGE}-ondemand" >> .env
    fi
    echo committing xdmod
    docker commit xdmod ${XDMOD_ONDEMAND_IMAGE}-test-ondemand
    echo commited xdmod image
    if grep -q '^ONDEMAND_TESTBUILD=' .env;
    then
      sed -i~ '/^ONDEMAND_TESTBUILD=/s/=.*/=${XDMOD_ONDEMAND_IMAGE}-test-ondemand/' .env
    else
      echo "ONDEMAND_TESTBUILD=${XDMOD_ONDEMAND_IMAGE}-test-ondemand" >> .env
    fi
}

# stops containers
stop() {
    export COMMAND=''
    docker-compose down
}

case "$1" in
    'start')
        start
        ;;
    'build')
        build
        ;;
    'testbuild')
        testbuild
        ;;
    'stop')
        stop
        ;;
    *)
        log_info "Usage: $0 { start | build | testbuild | stop }"
        exit 1
        ;;
esac