#!/bin/bash

log_info() {
    printf "\n\e[0;35m $1\e[0m\n\n"
}

log_warn() {
    printf "\e[0;33m $1\e[0m\n"
}

# starts existing image
start() {
    export XDMOD_ONDEMAND_IMAGE=$1
    export MARIADB_IMAGE=$2
    export COMMAND="start"
    docker-compose up -d
}


build() {
    export MARIADB_IMAGE=$1
    export COMMAND="build"
    docker-compose up -d
}

# stops containers
stop() {
    export COMMAND=''
    docker-compose down
}

case "$1" in
    'start')
        if [[ "$2" ]] && [[ "$3" ]]
        then
            start "$2" "$3"
        else
            log_info "Usage: $0 { start { xdmod-ondemand image | mariadb-ondemand image } }"
            exit 1
        fi
        ;;
    'build')
        if [[ "$2" ]]
        then
            build "$2"
        else
            log_info "Usage: $0 { build { mariadb image } }"
            exit 1
        fi
        ;;
    'stop')
        stop
        ;;
    *)
        log_info "Usage: $0 { start { xdmod-supremm image | mariadb-supremm image } | build { mariadb image } | stop }"
        exit 1
        ;;
esac