services:
  xdmod:
    depends_on:
      mariadb:
        condition: service_healthy
    hostname: xdmod
    container_name: xdmod
    image: ${XDMOD_IMAGE}
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    ports:
      - '443:443'
    volumes:
      - ./bin:/root/bin
      - ./xdmod/tests/ci/bootstrap.sh:/root/xdmod/tests/ci/bootstrap.sh
      - ./xdmod:/root/xdmod
    mem_reservation: 2G
    networks:
      xdmod_default: {}

  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: ${MARIADB_IMAGE}
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      xdmod_default: {}

networks:
  xdmod_default:
    name: xdmod_default

