services:
  xdmod:
    depends_on:
      mariadb:
        condition: service_healthy
    hostname: xdmod
    container_name: xdmod
    command: ${COMMAND}
    image:  ${XDMOD_IMAGE}
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    ports:
      - '443:443'
    mem_reservation: 2G
    networks:
      xdmod_default: {}

  mariadb:
    image: ${MARIADB_IMAGE}
    container_name: mariadb
    hostname: mariadb
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--connect", "--innodb_initialized",  "--datadir", "/var/lib/db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      xdmod_default: {}

networks:
  xdmod_default:
    name: xdmod_default