#!/bin/bash

log_info() {
    printf "\n\e[0;35m $1\e[0m\n\n"
}

log_warn() {
    printf "\e[0;33m $1\e[0m\n"
}

# starts exisiting image
start() {
    source .env
    export XDMOD_IMAGE=${XDMOD_BUILD}
    export MARIADB_IMAGE=${MARIADB_BUILD}
    export COMMAND="start"
    docker-compose up -d
}

starttest() {
    source .env
    export XDMOD_IMAGE=${XDMOD_TESTBUILD}
    export MARIADB_IMAGE=${MARIADB_TESTBUILD}
    export COMMAND="start"
    docker-compose up -d
}

# builds xdmod with just tables
build() {
    source .env
    export COMMAND="build"
    docker-compose up -d
    dots="."
      while ! curl --insecure --output /dev/null --silent --head --fail "https://localhost";
      do
        echo -ne "waiting for server to be up $dots\033[0K\r"
        sleep 1s
        dots="$dots."
        if [ ${#dots} -gt 3 ]; then
            dots="."
        fi
      done
      echo -e "\nServer is up!"
    echo committing mariadb
    docker commit mariadb "${MARIADB_IMAGE}"-build
    echo commited mariadb image
    if grep -q '^MARIADB_BUILD=' .env;
    then
      sed -i~ '/^MARIADB_BUILD=/s/=.*/=${MARIADB_IMAGE}-build/' .env
    else
      echo "MARIADB_BUILD=${MARIADB_IMAGE}-build" >> .env
    fi
    echo committing xdmod
    docker commit xdmod ${XDMOD_IMAGE}-build
    echo commited xdmod image
    if grep -q '^XDMOD_BUILD=' .env;
    then
      sed -i~ '/^XDMOD_BUILD=/s/=.*/=${XDMOD_IMAGE}-build/' .env
    else
      echo "XDMOD_BUILD=${XDMOD_IMAGE}-build" >> .env
    fi
}

# builds xdmod with test data
testbuild() {
    source .env
    export XDMOD_IMAGE=${XDMOD_BUILD}
    export MARIADB_IMAGE=${MARIADB_BUILD}
    export COMMAND="testbuild"
    docker-compose up -d
    dots="."
    while ! curl --insecure --output /dev/null --silent --head --fail "https://localhost";
    do
      echo -ne "waiting for server to be up $dots\033[0K\r"
      sleep 1s
      dots="$dots."
      if [ ${#dots} -gt 3 ]; then
          dots="."
      fi
    done
    echo -e "\nServer is up!"
    echo committing mariadb
    docker commit mariadb "${MARIADB_IMAGE}"-test
    echo commited mariadb image
    if grep -q '^MARIADB_TESTBUILD=' .env;
    then
      sed -i~ '/^MARIADB_TESTBUILD=/s/=.*/=${MARIADB_IMAGE}-test/' .env
    else
      echo "MARIADB_TESTBUILD=${MARIADB_IMAGE}-test" >> .env
    fi
    echo committing xdmod
    docker commit xdmod ${XDMOD_IMAGE}-test
    echo commited xdmod image
    if grep -q '^XDMOD_TESTBUILD=' .env;
    then
      sed -i~ '/^XDMOD_TESTBUILD=/s/=.*/=${XDMOD_IMAGE}-test/' .env
    else
      echo "XDMOD_TESTBUILD=${XDMOD_IMAGE}-test" >> .env
    fi
}

# stops containers
stop() {
    export COMMAND=''
    docker-compose down
}

case "$1" in
    'start')
        if grep -q '^MARIADB_BUILD=' .env;
        then
            start
        else
            log_info "Usage: $0 { start { build first } }"
            exit 1
        fi
        ;;
    'starttest')
            if grep -q '^MARIADB_TESTBUILD=' .env;
            then
                start
            else
                log_info "Usage: $0 { starttest { build testbuild first } }"
                exit 1
            fi
            ;;
    'build')
        build
        ;;
    'testbuild')
        if grep -q '^MARIADB_BUILD=' .env;
        then
            testbuild "$2" "$3"
        else
            log_info "Usage: $0 { build first } }"
            exit 1
        fi
        ;;
    'stop')
        stop
        ;;
    *)
        log_info "Usage: $0 { start { build first } | starttest { build testbuild first } | build | testbuild { build first } | stop }"
        exit 1
        ;;
esac