services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    healthcheck:
      test: [ "CMD", "mongo", "--username", "root", "--password", "admin", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      xdmod_default: {}

  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: tools-int-01.ccr.xdmod.org/mariadb:x86_64-rockylinux8.5-01-populated3
    restart: always
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--connect", "--innodb_initialized",  "--datadir", "/var/lib/db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    networks:
      xdmod_default: {}

  xdmod:
    image: ${XDMOD_JOB_PERFORMANCE_IMAGE}
    container_name: xdmod
    hostname: xdmod
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    volumes:
      - ./xdmod-supremm:/root/xdmod-supremm
      - ./xdmod-setup.tcl:/root/xdmod-setup.tcl
    networks:
      xdmod_default: {}

networks:
  xdmod_default:
    name: xdmod_default


volumes:
  mongo-data: