services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo-data:/data/db
    networks:
      xdmod_default: {}

  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: ${MARIADB_IMAGE}
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      xdmod_default: {}

  xdmod-job-performance:
    image: ${XDMOD_JOB_PERFORMANCE_IMAGE}
    container_name: xdmod-job-performance
    hostname: xdmod-job-performance
    depends_on:
      mongodb:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    networks:
      xdmod_default: {}

networks:
  xdmod_default:
    name: xdmod_default


volumes:
  mongo-data:
