services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: xdmod
      MONGO_INITDB_ROOT_PASSWORD: uvVA6bIC9DMts30ZiLRaH
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    #volumes:
    #  - ./bin/mongodbaccountcreation.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    networks:
      xdmod_default: {}

  mariadb:
    hostname: mariadb
    container_name: mariadb
    image: tools-int-01.ccr.xdmod.org/mariadb:x86_64-rockylinux8.5-01-general2
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--connect", "--innodb_initialized",  "--datadir", "/var/lib/db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      xdmod_default: {}

  xdmod-job-performance:
    image: ${XDMOD_JOB_PERFORMANCE_IMAGE}
    container_name: xdmod-job-performance
    hostname: xdmod-job-performance
    depends_on:
      mongodb:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    networks:
      xdmod_default: {}

networks:
  xdmod_default:
    name: xdmod_default


volumes:
  mongo-data:
