services:
  mongodb:
    image: mongo:5.0
    healthcheck:
      test: [ "CMD", "mongo", "--username", "root", "--password", "admin", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      xdmod_default: {}

  mariadb:
    image: ${MARIADB_IMAGE}
    healthcheck:
      test: [ "CMD", "/usr/local/bin/healthcheck.sh", "--connect", "--innodb_initialized",  "--datadir", "/var/lib/db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      xdmod_default: {}

  xdmod:
    image: ${XDMOD_JOB_PERFORMANCE_IMAGE}
    container_name: xdmod
    hostname: xdmod
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    networks:
      xdmod_default: {}

networks:
  xdmod_default:
    name: xdmod_default


volumes:
  mongo-data: